DROP DATABASE IF EXISTS mutuellemobile;
CREATE DATABASE mutuellemobile;
CREATE TABLE etudiant(
ID integer primary key NOT NULL AUTO_INCREMENT,
NOM VARCHAR(100),
PRENOM VARCHAR(100),
ADRESSE VARCHAR(100),
EMAIL VARCHAR(100) UNIQUE NOT NULL,
TELEPHONE VARCHAR(10),
DATENAISSSANCE DATE);
CREATE TABLE formation(
ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
LIBELLE VARCHAR(100) NOT NULL,
DESCRIPTION VARCHAR(300));
CREATE TABLE inscription(
ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
dateinscription DATE,
statuTinscription VARCHAR(100),
anneeacademique VARCHAR(100),
ID_ETUDIANT INTEGER
FOREIGN KEY(ID_ETUDIANT) REFERENCES etudiant(ID),
ID_FORMATION INTEGER
FOREIGN KEY(ID_FORMATION) REFERENCES formation(ID),);